name: Build API 

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase repository name
        run: |
          REPO_NAME=${{ github.repository }} 
          echo "REPO_NAME_LC=${REPO_NAME,,}" >>${GITHUB_ENV}

      - name: Build API 
        run: |
          docker build -t ghcr.io/$REPO_NAME_LC:latest .

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/$REPO_NAME_LC:latest
